import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

import Footer from "@/components/navigator/Footer";
import Header from "@/components/navigator/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}
          strategy="afterInteractive"
        />
      </head>

      <body className="antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
